### ISSUE TITLE
 ReferenceError: Relationships is not defined at server/js/startup.js

### ISSUE THREAD

**Issue by p4cm4n** [ruler88/twitterClone#1]
In chapter 5 i get the  "ReferenceError: Relationships is not defined at server/js/startup.js" when i add the following:

``` javascript
Meteor.startup(function () {
  Relationships._ensureIndex({follower: 1, following: 1}, {unique: 1});
});
```

my undestranding of other languages tells me that this is a call to [db.collection.ensureindex](http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/) how can i change this in startup.js so the app runs correctly?

Thank you very much for your amazing work :)

**Comment by ruler88** [comment]
The error is saying that the collection store 'Relationships' was not defined at the point that startup ran.

1) Check that you already saved the file lib/collections/relationships.js The content is simply defining a new mongo collection: 
`Relationships = new Meteor.Collection("relationships");`

2) It is also important to make sure that the relationships.js file is in the lib folder. You can't defined the file load order in Meteor, you have to follow the load order defined by Meteor. (http://stackoverflow.com/questions/10109176/ordering-of-the-css-and-js-files-loaded-by-meteor) And the lib folder is loaded before the server/js folder.

Hope that helps!

**Comment by p4cm4n** [comment]
Totally missed that step, thank you, now it works perfectly! :smile:
